# Generated by Django 4.2.28 on 2026-03-02 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blind_eternities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.URLField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object', models.CharField(default='set', max_length=25)),
                ('code', models.CharField(db_index=True, help_text='Set Code', max_length=10, unique=True)),
                ('mtgo_code', models.CharField(blank=True, max_length=10, null=True)),
                ('arena_code', models.CharField(blank=True, max_length=10, null=True)),
                ('tcgplayer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('set_type', models.CharField(db_index=True, max_length=50)),
                ('released_at', models.DateField(blank=True, db_index=True, null=True)),
                ('block_code', models.CharField(blank=True, db_index=True, help_text='Block Code', max_length=10, null=True)),
                ('parent_set_code', models.CharField(blank=True, db_index=True, help_text='Parent set code', max_length=6, null=True)),
                ('card_count', models.PositiveIntegerField(default=0)),
                ('printed_size', models.PositiveIntegerField(blank=True, null=True)),
                ('digital', models.BooleanField(default=False)),
                ('nonfoil_only', models.BooleanField(default=False)),
                ('foil_only', models.BooleanField(default=False)),
                ('has_commanders', models.BooleanField(default=True)),
                ('uri', models.URLField(blank=True, max_length=500, null=True)),
                ('scryfall_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('search_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('icon_svg_uri', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
