# Generated by Django 4.2.28 on 2026-03-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_eternities', '0002_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='block',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
