# Generated by Django 4.2.28 on 2026-03-03 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blind_eternities', '0004_card_relatedcard_cardface_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(max_length=20)),
                ('published_at', models.DateField()),
                ('comment', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulings', to='blind_eternities.card')),
            ],
            options={
                'verbose_name': 'Ruling',
                'verbose_name_plural': 'Rulings',
                'unique_together': {('oracle_id', 'published_at', 'comment')},
            },
        ),
    ]
