# Generated by Django 4.2.28 on 2026-03-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blind_eternities', '0005_ruling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='banned_as_commander',
        ),
    ]
