# Generated by Django 4.2.28 on 2026-03-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_eternities', '0006_remove_card_banned_as_commander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='code',
            field=models.CharField(db_index=True, help_text='Set Code', max_length=10),
        ),
    ]
