# Generated by Django 4.2.28 on 2026-02-26 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('rank_0', 'Germ'), ('rank_1', 'Newt'), ('rank_2', 'Minion'), ('rank_3', 'Sleeper Agent'), ('rank_4', 'Overlord'), ('rank_5', 'Preaetor')], default='rank_1', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biography')),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('twitch', models.CharField(blank=True, max_length=150)),
                ('instagram', models.CharField(blank=True, max_length=150)),
                ('tiktok', models.URLField(blank=True, max_length=150)),
                ('facebook', models.URLField(blank=True, max_length=150)),
                ('other', models.URLField(blank=True, max_length=150)),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('total_wins', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from', to='multiverse.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to', to='multiverse.profile')),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relationships',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='multiverse.Relationship', to='multiverse.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['from_profile', 'to_profile'], name='multiverse__from_pr_67355b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('from_profile', 'to_profile')},
        ),
    ]
