# Generated by Django 4.2.28 on 2026-02-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='player_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
